[tenjin]
title = Tenjin
help = Settings for Tenjin extension
group = Analytics

sdk_key.type = string
sdk_key.default =
sdk_key.label = SDK key

app_store.type = string_array
app_store.options = googleplay: Google Play, amazon: Amazon, other: Other
app_store.default = googleplay
app_store.label = App Store
